### PR TITLE
chore(deps): update syn requirement from 1.0 to 2.0

### PR DESCRIPTION
**Pull request by pickfire**
Superseeds https://github.com/bytedance/monoio/pull/156

Some parts taken from https://github.com/tokio-rs/tokio/pull/5572

### CODE REVIEW

**Comment by ihciah** [comment]
Hi~ Thanks for your contribution, could you fix the clippy warning in CI?

**Comment by pickfire** [comment]
Sorry, just have the time to do it, I believe it's fixed now.

**Comment by ihciah** [comment]
There seems to be something wrong with the latest version of clippy. It suggest using `Vec<MaybeUninit<T>>` when `with_capacity() and then set_init()` in docs, but infact it gives warning.
Could you please help ignore it like adding `#[allow(clippy::uninit_vec)]` or some other ways?

**Comment by pickfire** [comment]
I believe this should be fixed in https://github.com/rust-lang/rust-clippy/issues/10565, should we wait? I guess not since even with the latest clippy we still have this issue. I ping them in the pull request.

**Review by ihciah — APPROVED** [review]

**Pull request merged**
