### PR TITLE
write stub code for pass compile on windows system

### PR DESCRIPTION
**Pull request by LemonHX**

### CODE REVIEW

**Comment by ihciah** [comment]
Please resolve conflicts. And by the way, after the code can compile on windows, can you setup a github action to test it?
(I resolved the conflicts locally and verifed the code does not affect linux.)

**Comment by LemonHX** [comment]
ok, i will do it tomorrow, and by the way, for tests i'd better to just modify the macro itself for less change.

**Comment by pymongo** [comment]
I suggest you to edit to document, add windows support to document. e.g. add windows to this line

> https://github.com/bytedance/monoio/blob/db04cb2bbe98265fd87a10a4d0428761a71e34f8/README.md?plain=1#L34

**Comment by ihciah** [comment]
It seems an extra \r\n...

**Comment by LemonHX** [comment]
> I suggest you to edit to document, add windows support to document. e.g. add windows to this line
> 
> > https://github.com/bytedance/monoio/blob/db04cb2bbe98265fd87a10a4d0428761a71e34f8/README.md?plain=1#L34

done

**Review by ihciah — APPROVED** [review]

**Pull request merged**
