### PR TITLE
[ISSUE #231] Enhance CI

### PR DESCRIPTION
**Pull request by loongs-zhang**
It seems that there is still a lot of work to do, CI fails in many arch.

Is it correct to use `"${CARGO}" test --target "${TARGET}" --no-default-features --features "async-cancel,bytes,legacy,macros,utils" --release` for testing? @ihciah

For windows, I want to use [polling](https://crates.io/crates/polling/2.8.0) as `LegacyDriver`, it works well in my crate.

### CODE REVIEW

**Comment by ihciah** [comment]
For now windows is not supported.
The ci in this pr seems uses `--all-features`, so the `unstable` is also enabled on stable toolchain, so it fails. Manually enabling features should be fine.

Another issue I want to solve is to test different features matrix. It maybe related to your work. For example, 1. only enabled uring driver 2. enable uring+legacy driver 3. only enable legacy driver. Last week I added a `poll-io` feature, so now there are more types of feature combinations. Do you have some ideas about it?

**Comment by loongs-zhang** [comment]
> For now windows is not supported. The ci in this pr seems uses `--all-features`, so the `unstable` is also enabled on stable toolchain, so it fails. Manually enabling features should be fine.

Argee with  manually enable `unstable` and I want to try to impl the windows part for monoio.

> Another issue I want to solve is to test different features matrix. It maybe related to your work. For example, 1. only enabled uring driver 2. enable uring+legacy driver 3. only enable legacy driver. Last week I added a `poll-io` feature, so now there are more types of feature combinations. Do you have some ideas about it?

For x86_64/i686 in linux , add `1. only enabled uring driver 2. enable uring+legacy driver 3. only enable legacy driver`;
For the rest arch in linux and windows/macos , just `3. only enable legacy driver`.
It seems that other CPU architectures in linux do not support io_uring, take a look at https://github.com/bytedance/monoio/actions/runs/7742353279/job/21111296816

Can `"${CARGO}" test --target "${TARGET}" --no-default-features --features "async-cancel,bytes,legacy,macros,utils" --release` test `3. only enable legacy driver`?

**Comment by ihciah** [comment]
> Can `"${CARGO}" test --target "${TARGET}" --no-default-features --features "async-cancel,bytes,legacy,macros,utils" --release` test `3. only enable legacy driver`?

Yes.

**Comment by loongs-zhang** [comment]
Due to https://github.com/nix-rust/nix/issues/2305, we will not add `loongarch64-unknown-linux-gnu` CI for now.

**Comment by loongs-zhang** [comment]
I think this PR is ready to merge @ihciah

**Comment by Miaxos** [comment]
Why not adding `aarch64-apple-darwin`? It seems the runners are using M1 now for `macos-14` so we should be able to build it directly and test it no?

**Comment by loongs-zhang** [comment]
> Why not adding `aarch64-apple-darwin`? It seems the runners are using M1 now for `macos-14` so we should be able to build it directly and test it no?

see https://github.com/bytedance/monoio/actions/runs/7773163800/job/21196501840?pr=236

**Comment by Miaxos** [comment]
https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/

>The macOS 14 runner image is now available for GitHub hosted runners. Workflows executed on this image will run exclusively on the 3 vCPU M1 runner announced earlier today. To use the runner, simply update the runs-on: key in your YAML workflow file to macos-14, macos-14-xlarge, or macos-14-large.

>The macOS 12 runner image will remain latest until migration of the latest YAML workflow label to macOS 14 in Q2 FY24 (April – June 2024). While macOS 13 is now generally available under the macos-13 label, this image will not be migrated to latest. Following this announcement, macOS 11 runner image will begin deprecation immediately with retirement expected to complete by June 2024.

You should put `macos-14` if you want your workflow to be run on a M1 aarch64 architecture

(If it still doesn't work idk haha)

**Comment by loongs-zhang** [comment]
It looks very nice ! @Miaxos

**Review by ihciah — APPROVED** [review]

**Pull request merged**
